phpfpm:  
  command: php-fpm --allow-to-run-as-root
  image: torniker/phpfpm-5.6
  volumes:
    - docker/fpm.conf:/usr/local/etc/php-fpm.conf
    - docker/php.ini:/usr/local/etc/php/php.ini
    - ./:/var/www/html
  links:
     - mysql
     - redis
  privileged: true

nginx:
  image: nginx:1.9.0
  volumes:
    - docker/nginx.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www
  ports:
   - "80:80"
  links:
   - phpfpm

mysql:
  command: mysqld --user=root --verbose
  image: mysql
  volumes:
    - docker/mysql.cnf:/etc/mysql/my.cnf
  environment:
    MYSQL_DATABASE: koko
    MYSQL_USER: dev
    MYSQL_PASSWORD: SomeDevPass
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
  ports:
   - "3306:3306"

redis:
  image: redis

node:
  command: node socket.js
  image: node
  working_dir: /var/www/html
  volumes:
    - ./:/var/www/html
  environment:
    REDIS_HOST: redis
  ports:
    - "3000:3000"
  links:
    - redis